In [12]:
import pandas as pd
import numpy as np
df = pd.read_csv("Data.csv")
start = pd.to_datetime("2020-01-01")
end = pd.to_datetime("2020-12-31")
df["Date"] = pd.to_datetime(
    np.random.randint(start.value, end.value, size=len(df))
)
df=df
df.to_csv("Data.csv",index=False)

In [18]:
# Read a CSV file of sales data, display the first 10 rows, and summarize sales by month.
import pandas as pd
df=pd.read_csv("Data.csv")
df.head(10)

,Product_Name,Sales,Date
0,The Ultimate History Buff Challenge: Over 600 ...,13.79,2020-01-09 13:00:11.331491916
1,The Ultimate Book of Random Fun Facts: Over 10...,12.72,2020-01-06 10:53:04.688776933
2,Winter Flurries of Fun: Flurries of snow outsi...,12.00,2020-06-21 05:17:08.128903868
3,Book Lovers Cut & Collage Ephemera: 275+ High-...,19.99,2020-10-30 18:00:22.630857564
4,Family Vision Board Clip Art Book: Inspiring P...,11.99,2020-01-06 22:11:23.464886530
5,The Movement Mastery Collection,18.99,2020-11-02 11:46:41.022966222
6,Baseball Obscura 2026,17.66,2020-07-13 09:15:23.118311828
7,2026 Interior Design Trends Magazine: From Qui...,15.49,2020-02-29 04:07:28.696530461
8,"SUMMER ADVENTURE LIST,ITALY",15.99,2020-06-29 12:58:15.583522232
9,I Spy Dinosaurs: Find the Dino friends playing...,13.99,2020-09-05 19:43:48.815023327

In [20]:
df["Date"]=pd.to_datetime(df["Date"])
df["Month"] = df["Date"].dt.month
df.to_csv("Data.csv",index=False)

In [21]:
salesByMonth = df.groupby("Month")["Sales"].sum().sort_index()
print(salesByMonth)

Month
1      407.58
2     1036.20
3     2870.60
4        7.99
5     1345.28
6      653.28
7      777.93
8      980.44
9      438.44
10    2030.32
11     427.31
12     157.54
Name: Sales, dtype: float64

In [ ]:
# Read an Excel file containing employee records and list all employees in a specific department.
import pandas as pd
data = {
    "Name": ["Anil Sharma","Priya Koirala","Ramesh Thapa","Sita Rai","Deepak Shrestha",
             "Manisha Gurung","Rajiv Khadka","Sunita Lama","Bikash Adhikari","Nisha Tamang",
             "Arun Poudel","Kritika Basnet","Santosh Karki","Meena Maharjan","Prakash Joshi",
             "Alisha Shrestha","Suraj Bhandari","Rupa Magar","Krishna KC","Binita Oli"],
    "Salary": [45000,55000,60000,42000,70000,
               48000,52000,46000,65000,40000,
               58000,44000,72000,50000,53000,
               47000,68000,43000,56000,49000],
    "Department": ["HR","Finance","IT","Marketing","IT",
                   "HR","Finance","Marketing","IT","HR",
                   "Finance","Marketing","IT","HR","Finance",
                   "Marketing","IT","HR","Finance","Marketing"]
}

df = pd.DataFrame(data)

df.to_excel("employees.xlsx", sheet_name="EmployeeData", index=False, engine="openpyxl")

In [11]:
df=pd.read_excel("employees.xlsx")
group=df.groupby("Department")["Name"].apply(list)
group

Department
Finance      [Priya Koirala, Rajiv Khadka, Arun Poudel, Pra...
HR           [Anil Sharma, Manisha Gurung, Nisha Tamang, Me...
IT           [Ramesh Thapa, Deepak Shrestha, Bikash Adhikar...
Marketing    [Sita Rai, Sunita Lama, Kritika Basnet, Alisha...
Name: Name, dtype: object

In [5]:
# Read a JSON file of product information and extract product names and prices.
import json
with open("product.json","r") as f:
    json_data=json.load(f)
for data in json_data:
    print(f"Product : {data['name']} , Price : {data['price']}")

Product : Laptop , Price : 75000
Product : Smartphone , Price : 45000
Product : Headphones , Price : 3000
Product : Keyboard , Price : 1500
Product : Mouse , Price : 1200
Product : Monitor , Price : 18000
Product : Printer , Price : 12000
Product : Desk Chair , Price : 8000
Product : Office Desk , Price : 15000
Product : Water Bottle , Price : 500
Product : Backpack , Price : 2500
Product : Shoes , Price : 4000
Product : T-Shirt , Price : 800
Product : Jeans , Price : 2500
Product : Watch , Price : 6000
Product : Table Lamp , Price : 2000
Product : Bookshelf , Price : 7000
Product : Notebook , Price : 150
Product : Pen Set , Price : 100
Product : Earbuds , Price : 2200

In [ ]:
# Fetch data from a public API (weather, COVID-19, etc.) and display it in a DataFrame.
import requests
import pandas as pd
url = "https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&hourly=temperature_2m"
response = requests.get(url)
data = response.json()
hourly_data = data["hourly"]
df=pd.DataFrame(hourly_data)
df.head()

               time  temperature_2m
0  2026-04-19T00:00            15.5
1  2026-04-19T01:00            14.9
2  2026-04-19T02:00            14.6
3  2026-04-19T03:00            14.3
4  2026-04-19T04:00            13.6