In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("Data.csv")
start = pd.to_datetime("2020-01-01")
end = pd.to_datetime("2020-12-31")
df["Date"] = pd.to_datetime(
    np.random.randint(start.value, end.value, size=len(df))
)
df=df
df.to_csv("Data.csv",index=False)

In [2]:
# Read a CSV file of sales data, display the first 10 rows, and summarize sales by month.
import pandas as pd
df=pd.read_csv("Data.csv")
df.head(10)

,Product_Name,Sales,Date,Month
0,The Ultimate History Buff Challenge: Over 600 ...,13.79,2020-03-08 11:44:56.359379119,1
1,The Ultimate Book of Random Fun Facts: Over 10...,12.72,2020-01-30 13:45:45.118898649,1
2,Winter Flurries of Fun: Flurries of snow outsi...,12.00,2020-07-09 11:35:51.482151264,6
3,Book Lovers Cut & Collage Ephemera: 275+ High-...,19.99,2020-01-06 07:13:25.360049856,10
4,Family Vision Board Clip Art Book: Inspiring P...,11.99,2020-05-16 18:29:52.592090957,1
5,The Movement Mastery Collection,18.99,2020-07-18 22:23:40.423040986,11
6,Baseball Obscura 2026,17.66,2020-09-30 06:53:19.746734088,7
7,2026 Interior Design Trends Magazine: From Qui...,15.49,2020-08-13 11:33:39.670588539,2
8,"SUMMER ADVENTURE LIST,ITALY",15.99,2020-08-23 22:39:24.381125659,6
9,I Spy Dinosaurs: Find the Dino friends playing...,13.99,2020-05-21 16:46:09.079737897,9

In [3]:
df["Date"]=pd.to_datetime(df["Date"])
df["Month"] = df["Date"].dt.month
df.to_csv("Data.csv",index=False)

In [4]:
salesByMonth = df.groupby("Month")["Sales"].sum().sort_index()
print(salesByMonth)

Month
1      188.60
2      630.58
3      494.30
4     2358.86
5     1193.77
6      905.49
7     1216.02
8      186.96
9       17.66
10     713.56
11    1226.43
12    2000.68
Name: Sales, dtype: float64

In [ ]:
# Read an Excel file containing employee records and list all employees in a specific department.
import pandas as pd
data = {
    "Name": ["Anil Sharma","Priya Koirala","Ramesh Thapa","Sita Rai","Deepak Shrestha",
             "Manisha Gurung","Rajiv Khadka","Sunita Lama","Bikash Adhikari","Nisha Tamang",
             "Arun Poudel","Kritika Basnet","Santosh Karki","Meena Maharjan","Prakash Joshi",
             "Alisha Shrestha","Suraj Bhandari","Rupa Magar","Krishna KC","Binita Oli"],
    "Salary": [45000,55000,60000,42000,70000,
               48000,52000,46000,65000,40000,
               58000,44000,72000,50000,53000,
               47000,68000,43000,56000,49000],
    "Department": ["HR","Finance","IT","Marketing","IT",
                   "HR","Finance","Marketing","IT","HR",
                   "Finance","Marketing","IT","HR","Finance",
                   "Marketing","IT","HR","Finance","Marketing"]
}

df = pd.DataFrame(data)

df.to_excel("employees.xlsx", sheet_name="EmployeeData", index=False, engine="openpyxl")

In [11]:
df=pd.read_excel("employees.xlsx")
group=df.groupby("Department")["Name"].apply(list)
group

Department
Finance      [Priya Koirala, Rajiv Khadka, Arun Poudel, Pra...
HR           [Anil Sharma, Manisha Gurung, Nisha Tamang, Me...
IT           [Ramesh Thapa, Deepak Shrestha, Bikash Adhikar...
Marketing    [Sita Rai, Sunita Lama, Kritika Basnet, Alisha...
Name: Name, dtype: object

In [5]:
# Read a JSON file of product information and extract product names and prices.
import json
with open("product.json","r") as f:
    json_data=json.load(f)
for data in json_data:
    print(f"Product : {data['name']} , Price : {data['price']}")

Product : Laptop , Price : 75000
Product : Smartphone , Price : 45000
Product : Headphones , Price : 3000
Product : Keyboard , Price : 1500
Product : Mouse , Price : 1200
Product : Monitor , Price : 18000
Product : Printer , Price : 12000
Product : Desk Chair , Price : 8000
Product : Office Desk , Price : 15000
Product : Water Bottle , Price : 500
Product : Backpack , Price : 2500
Product : Shoes , Price : 4000
Product : T-Shirt , Price : 800
Product : Jeans , Price : 2500
Product : Watch , Price : 6000
Product : Table Lamp , Price : 2000
Product : Bookshelf , Price : 7000
Product : Notebook , Price : 150
Product : Pen Set , Price : 100
Product : Earbuds , Price : 2200

In [ ]:
# Fetch data from a public API (weather, COVID-19, etc.) and display it in a DataFrame.
import requests
url = "https://api.open-meteo.com/v1/forecast?latitude=52.52&longitude=13.41&hourly=temperature_2m"
response = requests.get(url)
data = response.json()
hourly_data = data["hourly"]
df=pd.DataFrame(hourly_data)
df.head()

               time  temperature_2m
0  2026-04-19T00:00            15.5
1  2026-04-19T01:00            14.9
2  2026-04-19T02:00            14.6
3  2026-04-19T03:00            14.3
4  2026-04-19T04:00            13.6

In [7]:
# Combine data from CSV and Excel files into a single DataFrame.
df1=pd.read_csv("Data.csv")

df2=pd.read_excel("employees.xlsx")
df = pd.concat([df1, df2], ignore_index=True)
df.head()

,Product_Name,Sales,Date,Month,Name,Salary,Department
0,The Ultimate History Buff Challenge: Over 600 ...,13.79,2020-03-08 11:44:56.359379119,3.0,NaN,NaN,NaN
1,The Ultimate Book of Random Fun Facts: Over 10...,12.72,2020-01-30 13:45:45.118898649,1.0,NaN,NaN,NaN
2,Winter Flurries of Fun: Flurries of snow outsi...,12.00,2020-07-09 11:35:51.482151264,7.0,NaN,NaN,NaN
3,Book Lovers Cut & Collage Ephemera: 275+ High-...,19.99,2020-01-06 07:13:25.360049856,1.0,NaN,NaN,NaN
4,Family Vision Board Clip Art Book: Inspiring P...,11.99,2020-05-16 18:29:52.592090957,5.0,NaN,NaN,NaN

In [ ]:
# Handle missing values in a dataset by filling with median values and verify the result.
import pandas as pd

df=pd.read_csv("dataa.csv",encoding="ISO-8859-1")
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [2]:
df.isna().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [3]:
df.shape

(541909, 8)

In [9]:
df["CustomerID"].fillna(df["CustomerID"].median,inplace=True)
df['Description'].fillna(df['Description'].mode()[0],inplace=True)

In [10]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [11]:
df.isna().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [12]:
df.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID      object
Country         object
dtype: object

In [6]:
for i in range(100,1000):
    if(i%2==1 and i%3==1 and i%4==1 and i%5==1 and i%6==1 and i%7==0):
        print(i)

301
721